### ISSUE TITLE
Swimlanes support

### ISSUE THREAD

**Issue by cypressbit** [EugeneTheDev/TaigaMobile#13]
Stories and swimlanes are not visible in the kanban board.

**Comment by EugeneTheDev** [comment]
There is no swimlines support yet. And what's wrong with stories? I've tested it with several taiga instances and everything was fine. Can you provide screenshot please?

**Comment by cypressbit** [comment]
Got it, that is probably why the stories are not showing up. I was referring to stories in swimlanes.

**Comment by EugeneTheDev** [comment]
This is not normal behavior at all. All stories must be visible. I have little test project with swimlines:
<img src="https://user-images.githubusercontent.com/36568187/122915524-7fd83c00-d364-11eb-9eb2-62ede154f318.png" width=400/>  
And all these stories are visible in app:  
<img src="https://user-images.githubusercontent.com/36568187/122915891-f2491c00-d364-11eb-9eee-02d5d97c9ae6.png" width=400/>

**Comment by TheJeje20** [comment]
Maybe I can add a little precision on that issue

I also use swimlanes through the web interface of Taiga. I noticed that only the first 40 tasks (all swimlanes) show up in TaigaMobile's Kanban view.

I have 76 tasks. All the 76 show up in the "Scrum" tab, but only the 40 first tasks show up in the Kanban.

**Comment by EugeneTheDev** [comment]
I've fixed original issue with missing stories on kanban board (see #15). Support for swimlines is on the way
