### ISSUE TITLE
Get endpoints pagination

### ISSUE THREAD

**Issue by cypper** [EugeneTheDev/TaigaMobile#15]
Get endpoints dont use pagination that why some resources may get lost

LIke this one for example - https://github.com/EugeneTheDev/TaigaMobile/blob/master/app/src/main/java/io/eugenethedev/taigamobile/data/api/TaigaApi.kt#L74

Here is a documentation for taiga pagination - https://docs.taiga.io/api.html#_pagination

I may be wrong, but in large projects kanban doesn't display all tickets

**Comment by EugeneTheDev** [comment]
Thanks for pointing that out. I was missing `x-disable-pagination` header for unpaginated requests
