### ISSUE TITLE
Could you build notification for mobile?

### ISSUE THREAD

**Issue by cmdntd** [EugeneTheDev/TaigaMobile#17]
I think notifications are very important for mobile app

**Comment by cmdntd** [comment]
Hope this soon.

I also see that Taiga does not have responsive. They must fix this in this term 6.
I think they should update everything for mobile soon in this term.

**Comment by EugeneTheDev** [comment]
I'm closing this issue because as for now it is not possible to implement this feature. Feel free to reopen if you have any ideas/suggestions or updates
