### ISSUE TITLE
LDAP Authentication

### ISSUE THREAD

**Issue by dl2v** [EugeneTheDev/TaigaMobile#18]
Can you add the ability to select LDAP authentication?
Thanks.

**Comment by EugeneTheDev** [comment]
I'm building app that is able to work with every Taiga instance. So app must be generic. But LDAP authentication is not standart Taiga functionality. So I do not think that this is acutally good idea.

**Comment by EugeneTheDev** [comment]
After a more thorough look at this problem I think that it will be possible to add support for LDAP auth without breaking compatibility with other Taiga instances
