### ISSUE TITLE
Private Projects Inaccessible

### ISSUE THREAD

**Issue by cathalgarvey** [EugeneTheDev/TaigaMobile#2]
Hi, firstly I'd just like to thank you for making something like this. The lack of a mobile application is the reason I don't really use Taiga, even though I love the design and functionality. It's really weird that they didn't offer an official FOSS mobile app. And creepy that the nearly-official app is secret-source. :/

Anyways, I fired this up and tried it, but I didn't get far: my only project on Taiga is a private one, and TaigaMobile only directs me to a list of public projects to pick from. So I couldn't go any further than that. :)

I'm not sure what it would take to add private project support, but the ideal pattern for usage for me would be to be presented with projects I'm already part of, before asking me if I want to join/view other public projects.

I'll keep the app for now and try out any updates that emerge, I'm excited to see where it goes. Thanks again!

**Comment by EugeneTheDev** [comment]
Hello, thanks for your feedback!
This issue was already reported and fixed. In next release everything should be ok

**Comment by cathalgarvey** [comment]
Wow, you work fast! :)

Sorry to duplicate, I'd checked issues in case it was already reported here, at least. Will eagerly await the next release on the IzzySoft repo: https://android.izzysoft.de/repo/apk/io.eugenethedev.taigamobile

**Comment by EugeneTheDev** [comment]
It's ok, this issue is not duplicate, problem was reported privately to me
