### ISSUE TITLE
Offline functionality

### ISSUE THREAD

**Issue by patogit** [EugeneTheDev/TaigaMobile#43]
Hi! Taiga looks really useful, and this app could make it even more useful. In my organization, we are sometimes offline for a week at a time. Therefore, we prefer apps that are functional offline, and can sync gracefully when they connect to the internet. I suspect that this would be a lot of work, given that Taiga seems to be designed so that everything happens on the server. Do you think there's any chance of offline functionality in this app?

**Comment by EugeneTheDev** [comment]
Although your point seems reasonable for some cases, I don't think that we would be able to implement any viable solution. 

The main problem, as you've already mentioned, is that everything is happening on the server. And so here's the synchronization problem: imagine that you edit the task, then someone from your team edits the same parameter of the same task. How the app should behave in this case? Apply only the latest change? But this leads to the unexpected behavior on your side (you check the task again, and it doesn't have the edit you've made). And how to determine the latest change? What if your change has been the latest, but your phone came online later than someone else’s? As you can see, there are a lot of questions and corner cases here. Also, as you've pointed out too, a lot of work is required for this functionality to be implemented. 

Given the above, while we might implement some caching mechanism in the future (like the majority of the apps do), I don't think that it is reasonable to bring fully offline mode to the app. Taiga itself just hasn't been designed for this.
