### ISSUE TITLE
app login not possible with subpath

### ISSUE THREAD

**Issue by deraljoscha** [EugeneTheDev/TaigaMobile#51]
Hey dear developer.
I love the app and recently tested it and then set taiga up for my small workplace. We installed Taiga under a subpath and everything works fine in the web version.
But unfortunately now the login through the app that previously worked perfectly fine under a subdomain doesn't work anymore.
So before it worked under taiga.mydomain.com and now doesn't work anymore under mydomain.com/taiga
The "taiga server url" field on the start screen of the app just comes up with an error (red frame)

So is there something I can do or is it something to fix easily?

Thanks so much in advance, I really appreciate the effort
![Screenshot_20220517-124648_WhatsApp](https://user-images.githubusercontent.com/105179047/168794193-f157670a-c56f-439b-84f9-2284ba2ac850.png)

**Comment by EugeneTheDev** [comment]
It's just a validation on my side. I'll fix it to allow subpaths

**Comment by EugeneTheDev** [comment]
That would be controversial feature request. Of course position of menu items is highly opinionated, but it's been like this for a long time and I bet a lot of users are used to it. Thus I'm not sure if it will be a good idea to change this order
