### ISSUE TITLE
#feature request: kanban to the front - change order - start page

### ISSUE THREAD

**Issue by deraljoscha** [EugeneTheDev/TaigaMobile#52]
Since my last problem was fixed so quickly I thought I'd ask for a feature request: I wanted to know if it's possible to add a possibility to change the order of the different boards (scrum, Epic, kanban etc) and/or to set a default page where the app always opens (for example kanban).

Thank you so much for your effort, I'm super happy there even is an app
Regards from Germany

Edited as asked for

**Comment by EugeneTheDev** [comment]
Can you please create separate issue for drag and drop functionality?

**Comment by deraljoscha** [comment]
I absolutely see the point, that users are used to the current order and tiles. So maybe then just a possibility to change the order manually and keep the order like it is by default so nothing changes for the users if they don't want it to.

**Comment by EugeneTheDev** [comment]
Unfortunately, I don't have resources to continue working on this project, so I'm closing this issue and archiving repository
