### ISSUE TITLE
Kanban support

### ISSUE THREAD

**Issue by Igorgro** [EugeneTheDev/TaigaMobile#6]
Kanban is one of the main features of Taiga agile. Are there any plans to implement it in this application?

**Comment by EugeneTheDev** [comment]
Already working on it https://tree.taiga.io/project/eugenethedev-taiga-mobile/us/16

**Comment by EugeneTheDev** [comment]
Check out new release: https://github.com/EugeneTheDev/TaigaMobile/releases/tag/v1.2
